### ISSUE TITLE
可以运行，但是一运行就报错。

### ISSUE THREAD

**Issue by renwood** [sunnyelf/cheetah#12]
Traceback (most recent call last):
  File "cheetah.py", line 547, in <module>
    main()
  File "cheetah.py", line 528, in main
    attack_res = dict_attack(options)
  File "cheetah.py", line 340, in dict_attack
    if detect_web(options) == 'error':
  File "cheetah.py", line 286, in detect_web
    random_str = str(random.sample(string.printable, 5)).encode('hex')
LookupError: 'hex' is not a text encoding; use codecs.encode() to handle arbitrary codecs

**Comment by shmilylty** [comment]
好的，之后我有时间看一下，谢谢反馈。 现在更多时间是在维护图形化用户界面版[https://github.com/sunnyelf/cheetah-gui](https://github.com/sunnyelf/cheetah-gui)，你可以看一下: )

**Comment by shmilylty** [comment]
大致看了一下，应该是与Python 3不兼容导致的，之后有空做一下兼容好了。

**Comment by tysmlq** [comment]
这个问题在windows下可以看到，无论py2还是3都有。但在kali下没问题
