### ISSUE TITLE
报错求解决

### ISSUE THREAD

**Issue by v2htw** [sunnyelf/cheetah#8]
C:\Users\Administrator\Desktop
> python E:\Tool\cheetah-webshell\cheetah.py -u http://192.168.36.202/xm.php

_________________________________________________
       ______              _____         ______
__________  /_ _____ _____ __  /_______ ____  /_
_  ___/__  __ \_  _ \_  _ \_  __/_  __ \ __  __ \
/ /__  _  / / //  __//  __// /_  / /_/ / _  / / /
\___/  / / /_/ \___/ \___/ \__/  \____/  / / /_/
      /_/                               /_/

a very fast brute force webshell password tool.

[11:18:25] [INFO] the cheetah start execution
[11:18:25] [HINT] using POST request mode
[11:18:25] [HINT] setting request interval seconds 0
[11:18:25] [HINT] using dictionary-based password attack
[11:18:25] [INFO] cracking password of http://192.168.36.202/xm.php
[11:18:25] [WARN] not specify the web server or shell type
[11:18:25] [INFO] detecting server info of http://192.168.36.202/xm.php
Traceback (most recent call last):
  File "E:\Tool\cheetah-webshell\cheetah.py", line 545, in <module>
    main()
  File "E:\Tool\cheetah-webshell\cheetah.py", line 526, in main
    attack_res = dict_attack(options)
  File "E:\Tool\cheetah-webshell\cheetah.py", line 338, in dict_attack
    if detect_web(options) == 'error':
  File "E:\Tool\cheetah-webshell\cheetah.py", line 246, in detect_web
    header = gen_random_header(options)
  File "E:\Tool\cheetah-webshell\cheetah.py", line 127, in gen_random_header
    with open('data/user-agent.list') as agent_file:
IOError: [Errno 2] No such file or directory: 'data/user-agent.list'
![image](https://user-images.githubusercontent.com/33211534/32153489-dc3400d8-bd65-11e7-96c3-d5ddd5bb8234.png)

**Comment by v2htw** [comment]
问题已解决：
01.必须使用python3
02.cheetah.py不能被修改，不能加入中文字符
03.可以运行，但是发现新问题如下
![image](https://user-images.githubusercontent.com/33211534/32154250-662d7036-bd6a-11e7-998e-26b08ac08ba8.png)

[11:54:08] [INFO] posting 343th group payload to http://192.168.36.202/xm.php
[11:54:08] [HINT] waiting for web server response
[11:54:08] [INFO] web server responds successfully
[11:54:08] [HINT] the password of http://192.168.36.202/xm.php not in 343 th group payload
Traceback (most recent call last):
  File "E:\Tool\cheetah-webshell爆破\cheetah.py", line 545, in <module>
    main()
  File "E:\Tool\cheetah-webshell爆破\cheetah.py", line 526, in main
    attack_res = dict_attack(options)
  File "E:\Tool\cheetah-webshell爆破\cheetah.py", line 356, in dict_attack
    for pwd in pwd_file:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 3481: illegal multibyte seq uence

**Comment by 0IJMLO03WSDR406TGHU70** [comment]
![image](https://user-images.githubusercontent.com/33211534/32154694-3adb8c94-bd6d-11e7-86b5-ea68c9d456f2.png)

**Comment by v2htw** [comment]
C:\Python34\python.exe E:\Tool\cheetah-webshell爆破\cheetah.py -u http://192.168.36.202/xm.ph
p

_________________________________________________
       ______              _____         ______
__________  /_ _____ _____ __  /_______ ____  /_
_  ___/__  __ \_  _ \_  _ \_  __/_  __ \ __  __ \
/ /__  _  / / //  __//  __// /_  / /_/ / _  / / /
\___/  / / /_/ \___/ \___/ \__/  \____/  / / /_/
      /_/                               /_/

a very fast brute force webshell password tool.

[12:29:11] [INFO] the cheetah start execution
[12:29:11] [HINT] using POST request mode
[12:29:11] [HINT] setting request interval seconds 0
[12:29:11] [HINT] using dictionary-based password attack
[12:29:11] [INFO] cracking password of http://192.168.36.202/xm.php
[12:29:11] [WARN] not specify the web server or shell type
[12:29:11] [INFO] detecting server info of http://192.168.36.202/xm.php
[12:29:11] [HINT] the shell type may be php
[12:29:12] [HINT] web server may be Apache/2.0.63 (Win32) PHP/5.2.14
[12:29:12] [HINT] web server may be x-powered-by PHP/5.2.14
[12:29:12] [WARN] you did not specify the maximum request parameter
[12:29:12] [INFO] setting the number of request parameters 1000
[12:29:12] [INFO] opening password file data/pwd.list
[12:29:12] [HINT] using password file data/pwd.list
[12:29:12] [INFO] cracking password of http://192.168.36.202/xm.php
Traceback (most recent call last):
  File "E:\Tool\cheetah-webshell爆破\cheetah.py", line 545, in <module>
    main()
  File "E:\Tool\cheetah-webshell爆破\cheetah.py", line 526, in main
    attack_res = dict_attack(options)
  File "E:\Tool\cheetah-webshell爆破\cheetah.py", line 356, in dict_attack
    for pwd in pwd_file:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 3481: illegal multibyte sequence

打算去试试别的：）

**Comment by v2htw** [comment]
kali下面使用非常流畅，完全没有报错，也许是我的windows下面缺少了什么东西 --！
